### ISSUE TITLE
About the system installation is the prompt "Sorry, the page you specified does not exist"

### ISSUE THREAD

**Issue by cocoakeer** [fbelavenuto/arpl#160] opened 2022-09-11 12:00 UTC
Hello!
       I am using arpl7 to compile and boot, and there is no problem in the process of making boot.
But I encountered a problem page prompting "Sorry, the page you specified does not exist" when the system was installed, and the prompt page appeared about 6 minutes left in the 10-minute countdown. What's the reason for that? Ask for your help and look forward to your reply. thank you very much.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/112269603/189526380-2cfb5c9f-b144-4a30-9a93-75c13a8019bb.png">

**Comment by cocoakeer** [comment] 2022-09-11 15:34
Hello, after repeated testing, I found that as long as I add the parameters of the nuclear display driver to compile, this phenomenon will occur, and there is no problem in deleting the nuclear display driver parameters.
My current CPU is Intel J4125
Looking forward to your reply, thank you very much.

**Comment by pepepej** [comment] 2022-09-11 20:48
I have the same problem, have you been able to solve it?

**Comment by cocoakeer** [comment] 2022-09-12 04:15
> 

Remove the driver parameters when compiling, or reboot into the BIOS, set the vt-d parameter to off, and try again.

**Comment by fbelavenuto** [comment] 2022-09-12 14:46
Hi, please test with the last alpha version:
https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7

**Comment by pepepej** [comment] 2022-09-12 15:44
> Hi, please test with the last alpha version: https://github.com/fbelavenuto/arpl/releases/tag/v0.4-alpha7
It is the version I have used. Thank you

**Comment by pepepej** [comment] 2022-09-12 15:45
> > 
> 
> Remove the driver parameters when compiling, or reboot into the BIOS, set the vt-d parameter to off, and try again.



> > 


The Bios thing hasn't worked, I'm going to try the other option. Thank you

**Comment by fbelavenuto** [comment] 2022-09-12 15:46
Test again, I've fixed the bug and recreated the v0.4-a7 release

**Comment by pepepej** [comment] 2022-09-12 17:35
> Test again, I've fixed the bug and recreated the v0.4-a7 release

It works now, I have compiled again with a 918+ that I had before, and not the 920+ that I wanted to install. And just keep the files. Thank you

**Comment by andreadaoud** [comment] 2022-09-13 10:37
@fbelavenuto Could you please assign a new version number each time you upload new release? If you don't want to increase alpha number, you can append a minor digit after it e.g. `0.4-alpha7-u1`. It is really confusing to upload with the same version number.

**Comment by fbelavenuto** [comment] 2022-09-13 11:24
Yes, I didn't realize that a lot of people used alpha7! It was a quick test of github actions and after re-using the same number I realized the confusion!

**Comment by cocoakeer** [comment] 2022-09-13 13:39
> 再次测试，我已经修复了错误并重新创建了v0.4-a7版本

Hello, today I use the latest program to test. It seems that the problem is still the same. At present, I use the v0.4-a7 version. The CPU of j4125 is installed with the latest version of Qunhui 7.1.1.

**Comment by cocoakeer** [comment] 2022-09-13 13:48
> > 再次测试，我已经修复了错误并重新创建了v0.4-a7版本
> 
> 您好，今天我使用最新的程序进行测试。看来问题还是一样的。目前，我使用的是 v0.4-a7 版本。j4125 的 CPU 与最新版本的群辉 7.1.1 一起安装。

Supplement: the test environment is compiled as 918+_42962

**Comment by fbelavenuto** [comment] 2022-09-13 13:50
Please check if addon "misc" was removed, look at "addons" menu

**Comment by fbelavenuto** [comment] 2022-09-13 14:03
Is correct! I'll study more to try found your trouble.

**Comment by cocoakeer** [comment] 2022-09-13 14:05
> Is correct! I'll study more to try found your trouble.

Thank you very much for your help and look forward to your good news. I will pay attention to it at any time. Thank you very, very much.

**Comment by cocoakeer** [comment] 2022-09-13 14:15
> Is correct! I'll study more to try found your trouble.

The reason why I pay attention to this problem is that I have been looking for the core display hardware decoding problem using the current J4125 cpu.

**Comment by cocoakeer** [comment] 2022-09-16 06:20
Hello, I don't know whether to fix this problem in the v0.4-a8 you just released. I plan to test it later.

**Comment by fbelavenuto** [comment] 2022-09-16 11:12
Hi, this release is to solve another problem, the installation loop. I believe it doesn't solve your problem but test it anyway!

**Comment by darkgetter** [comment] 2022-09-16 12:28
i have the same problem with alpha6, alpha7 & alpha8. i hope the problem will be solved soon.
Thank you for your effort. :) @fbelavenuto

**Comment by cocoakeer** [comment] 2022-09-16 13:11
> Hi, this release is to solve another problem, the installation loop. I believe it doesn't solve your problem but test it anyway!
Hello, after I tested the alpha 8 version, I found that the problem still exists. Thank you for your efforts.

**Comment by fbelavenuto** [comment] 2022-09-16 13:35
Thanks guys, I'll investigate more.

**Comment by cocoakeer** [comment] 2022-09-17 07:37
Hello, during my testing, I found that the esataportcfg parameter did not seem to take effect when compiling 920.

**Comment by darkgetter** [comment] 2022-09-20 04:04
![image](https://user-images.githubusercontent.com/13625341/191164467-df8907cc-794d-4c3a-8c2c-03a0ec026b70.png)
i've done some reading, finding out CPU-flag things being related to this "not found" situation.

information from coint_cho:
https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/82/#comment-274031
https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/84/#comment-274479
https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/93/#comment-275161

and info from pocopico:
https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/96/#comment-275465

i am looking forward to hearing from you, my NAS pc has been halted for 2 weeks more ... XD
again, thanks for your great work @fbelavenuto

**Comment by nomadism19** [comment] 2022-09-20 22:39
Booted smoothly until I need to install DSM via browser. Always installs to 56% then states "Failed to update the file. The file is probably corrupt." 2012 Mac mini i7, 16gb RAM, 2x 500gb Samsung SSDs. Tried different boot media (flash drives, an SSD), different computer (MacBook Air, MacBook Pro), different DSM models, no changes. Can I please get help? I have spent so many days trying to figure this out.

**Comment by cocoakeer** [comment] 2022-09-21 01:43
> Booted smoothly until I need to install DSM via browser. Always installs to 56% then states "Failed to update the file. The file is probably corrupt." 2012 Mac mini i7, 16gb RAM, 2x 500gb Samsung SSDs. Tried different boot media (flash drives, an SSD), different computer (MacBook Air, MacBook Pro), different DSM models, no changes. Can I please get help? I have spent so many days trying to figure this out.

I have encountered such situations before, and I think I can help you. You can try to install Pat by downloading the latest version from the official website. One way can solve this problem.

**Comment by fbelavenuto** [comment] 2022-09-23 20:13
> ![image](https://user-images.githubusercontent.com/13625341/191164467-df8907cc-794d-4c3a-8c2c-03a0ec026b70.png) i've done some reading, finding out CPU-flag things being related to this "not found" situation.
> 
> information from coint_cho: https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/82/#comment-274031 https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/84/#comment-274479 https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/93/#comment-275161
> 
> and info from pocopico: https://xpenology.com/forum/topic/53817-redpill-tinycore-loader/page/96/#comment-275465
> 
> i am looking forward to hearing from you, my NAS pc has been halted for 2 weeks more ... XD again, thanks for your great work @fbelavenuto

This fix is done by the "misc" addon, which is installed automatically!

**Comment by darkgetter** [comment] 2022-09-26 03:54
i confirmed that "misc" was added at each try since you had mentioned, but the problem remains 😢
is there anyone who have a solution?

**Comment by fbelavenuto** [comment] 2022-09-26 20:11
Guys, please update the Loader and Addons (or burn v0.4a12), add the addon "**dbgutils**", rebuild it and boots.
When the PC shutdown, please get the usb flash drive and check if exists a folder named "logs" in the first partition of flash drive (Windows S.O. recognize it), get the files and post here.

**Comment by darkgetter** [comment] 2022-09-27 11:33
here is my log
[logs_20220927.zip](https://github.com/fbelavenuto/arpl/files/9654988/logs_20220927.zip)

**Comment by fbelavenuto** [comment] 2022-09-27 14:21
> here is my log, thank you very much! [logs_20220927.zip](https://github.com/fbelavenuto/arpl/files/9654988/logs_20220927.zip)

@darkgetter Did you add the i915 addon?

**Comment by darkgetter** [comment] 2022-09-28 13:02
> > > @darkgetter Did you add the i915 addon?
> > 
> > 
> > yes. my CPU is i5-10400
> 
> Ok, please try remove addon and test if machine shutdown

thank you very very much, fabio @fbelavenuto 
i just removed the i915 addon, then the progress proceeds. 
problem solved. 😄 i am gonna try this i915 driver => https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/
again, thank you !!

**Comment by fbelavenuto** [comment] 2022-09-28 13:17
Ok, when we found a correct driver, I update the addon with the correct file.

**Comment by cocoakeer** [comment] 2022-09-29 08:37
Hello, everyone. I haven't had time to test recently. Is this problem solved? Is the 10th generation CPU driven?

**Comment by cocoakeer** [comment] 2022-09-29 08:41
> 大家好！我最近没有时间测试。这个问题解决了吗？第 10 代 CPU 是否由 CPU 驱动？

我当前用的cpu是J4125，集成显卡

**Comment by cocoakeer** [comment] 2022-09-29 09:07
> > Hello, everyone. I haven't had time to test recently. Is this problem solved? Is the 10th generation CPU driven?
> 
> 我的CPU是i5-10400，移除i915套件便可正常安裝了。 ( translate: my CPU is i5-10400, everything goes fine after removing i915 addon）

I'm talking about the removal of I915, but I can't hard solve it at present.

**Comment by darkgetter** [comment] 2022-09-29 09:29
> > > Hello, everyone. I haven't had time to test recently. Is this problem solved? Is the 10th generation CPU driven?
> > 
> > 
> > 我的CPU是i5-10400，移除i915套件便可正常安裝了。 ( translate: my CPU is i5-10400, everything goes fine after removing i915 addon）
> 
> I'm talking about the removal of I915, but I can't hard solve it at present.

你的內容是用機器翻譯的嗎? 你說是硬解吧
可測試 https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/

**Comment by cocoakeer** [comment] 2022-09-29 09:35
> > > > Hello, everyone. I haven't had time to test recently. Is this problem solved? Is the 10th generation CPU driven?
> > > 
> > > 
> > > 我的CPU是i5-10400，移除i915套件便可正常安裝了。 ( translate: my CPU is i5-10400, everything goes fine after removing i915 addon）
> > 
> > 
> > I'm talking about the removal of I915, but I can't hard solve it at present.
> 
> 你的內容是用機器翻譯的嗎? 你說是硬解吧 可測試 https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/
> 
> what cocoakeer means is if there is any approaches to Transcoding...

Unfortunately, it seems that I cannot find the core display driver corresponding to my CPU J4125. My core display device ID is 3185.

**Comment by andreadaoud** [comment] 2022-09-29 09:36
等作者更新了新版backport的i915驱动，应该就可以用了吧

When @fbelavenuto updates backported i915 driver, hardware transcoding will probably work

**Comment by cocoakeer** [comment] 2022-09-29 09:39
> 



> > > > > Hello, everyone. I haven't had time to test recently. Is this problem solved? Is the 10th generation CPU driven?
> > > > 
> > > > 
> > > > 我的CPU是i5-10400，移除i915套件便可正常安裝了。 ( translate: my CPU is i5-10400, everything goes fine after removing i915 addon）
> > > 
> > > 
> > > I'm talking about the removal of I915, but I can't hard solve it at present.
> > 
> > 
> > 你的內容是用機器翻譯的嗎? 你說是硬解吧 可測試 https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/
> > what cocoakeer means is if there is any approaches to Transcoding...
> 
> Unfortunately, it seems that I cannot find the core display driver corresponding to my CPU J4125. My core display device ID is 3185.



> 

在线等作者更新i915驱动，感谢，辛苦。（我一直在用翻译器^-^）

Online and other authors update the i915 driver, thanks for your hard work.(I have been using the translator ^ - ^)

**Comment by darkgetter** [comment] 2022-09-29 15:17
> Ok, when we found a correct driver, I update the addon with the correct file.

no luck with this -> https://xpenology.com/forum/topic/59909-i915ko-backported-driver-for-intel-10th-gen-ds918-ver-701-up3/

before migrating to DS920+, the hardware transcoding of DS918+ (DSM 6.2.4) only works properly with **v0.13.9 driver extensions**. this extension pack is not aimed for transcoding, but works. [_links of v0.13.9 ext.pack_](https://xpenology.com/forum/topic/28321-driver-extension-jun-103b104b-for-dsm623-for-918-3615xs-3617xs/)

logs of the above backport module from **_dmesg_** :

------------- 
[ 1484.815442] Module [i915] is removed. 
[ 1484.828766] Module [video] is removed. 
[ 1484.839825] Module [backlight] is removed. 
[ 1484.853868] Module [iosf_mbi] is removed. 
[ 1484.871802] Module [drm_kms_helper] is removed. 
[ 1484.886748] Module [drm] is removed. 
[ 1484.897727] Module [i2c_algo_bit] is removed. 
[ 1484.911764] Module [fb] is removed. 
[ 1489.090949] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[ 1489.098223] [drm] Driver supports precise vblank timestamp query.
[ 1489.105743] vgaarb: device changed decodes: PCI:0000:00:02.0,olddecodes=io+mem,decodes=io+mem:owns=io+mem
[ 1489.118494] BUG: unable to handle kernel NULL pointer dereference at           (null)
[ 1489.127118] IP: [<          (null)>]           (null)
[ 1489.129272] [drm] Finished loading DMC firmware i915/kbl_dmc_ver1_04.bin (v1.4)
[ 1489.140675] PGD 0 
[ 1489.142903] Oops: 0010 [#1] SMP 
[ 1489.146490] Modules linked in: i915(E+) video(E) backlight(E) iosf_mbi(E) drm_kms_helper(E) drm(E) i2c_algo_bit(E) fb(E) nfnetlink xfrm_user xfrm_algo fuse xt_ipvs ip_vs_rr ip_vs xt_mark iptable_mangle br_netfilter bridge stp aufs macvlan veth xt_conntrack xt_addrtype nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables ipt_MASQUERADE xt_REDIRECT nf_nat_masquerade_ipv4 xt_nat iptable_nat nf_nat_ipv4 nf_nat_redirect nf_nat xt_recent xt_iprange xt_limit xt_state xt_tcpudp xt_multiport xt_LOG nf_conntrack_ipv4 nf_defrag_ipv4 nf_conntrack iptable_filter ip_tables x_tables 8021q vhost_scsi(O) vhost(O) tcm_loop(O) iscsi_target_mod(O) target_core_user(O) target_core_ep(O) target_core_multi_file(O) target_core_file(O) target_core_iblock(O) target_core_mod(O) syno_extent_pool(PO) rodsp_ep(O) udf isofs
[ 1489.225250]  synoacl_vfs(PO) raid456 async_raid6_recov async_memcpy async_pq async_xor xor async_tx raid6_pq leds_lp3943 aesni_intel glue_helper lrw gf128mul ablk_helper geminilake_synobios(PO) usblp zram syscopyarea sysfillrect sysimgblt fb_sys_fops cfbfillrect cfbcopyarea cfbimgblt drm_panel_orientation_quirks fbdev uhci_hcd r8168(O) sg dm_snapshot dm_bufio crc_itu_t crc_ccitt psnap p8022 llc hfsplus md4 hmac sit tunnel4 ipv6 flashcache_syno(O) flashcache(O) syno_flashcache_control(O) dm_mod arc4 crc32c_intel cryptd ecb aes_x86_64 authenc des_generic ansi_cprng cts md5 cbc cpufreq_powersave cpufreq_performance processor cpufreq_stats ip_tunnel vfat fat loop sha256_generic synorbd(PO) synofsbd(PO) hid_generic usbhid usb_storage hid e1000e(OE) r8125(OE) ixgbe(OE) etxhci_hcd vxlan ip6_udp_tunnel udp_tunnel
[ 1489.303601]  button xhci_pci xhci_hcd ehci_pci ehci_hcd usbcore usb_common [last unloaded: fb]
[ 1489.311781] CPU: 3 PID: 21816 Comm: insmod Tainted: P           OE   4.4.180+ #42962
[ 1489.320252] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./Z490M-ITX/ac, BIOS P1.30 06/05/2020
[ 1489.330979] task: ffff880446278000 ti: ffff8804445d0000 task.ti: ffff8804445d0000
[ 1489.339178] RIP: 0010:[<0000000000000000>]  [<          (null)>]           (null)
[ 1489.347409] RSP: 0018:ffff8804445d38a0  EFLAGS: 00010246
[ 1489.353199] RAX: ffff8803df970040 RBX: ffff8803df97beb8 RCX: 0000000000000000
[ 1489.361013] RDX: 0000000000000000 RSI: ffff8803df970300 RDI: ffff8803df970040
[ 1489.368797] RBP: ffff8804445d38c8 R08: ffffffffa0e0e470 R09: ffff8803df970040
[ 1489.376622] R10: 0000000000001000 R11: 00000000fffff000 R12: ffff8803df970300
[ 1489.384417] R13: 0000000000000000 R14: ffff8803df97ba18 R15: ffff8803df97be78
[ 1489.392224] FS:  00007f7709923740(0000) GS:ffff88045c4c0000(0000) knlGS:0000000000000000
[ 1489.401070] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 1489.407306] CR2: 0000000000000000 CR3: 0000000420ec3000 CR4: 00000000003606f0
[ 1489.415103] Stack:
[ 1489.417305]  ffffffff812e12b1 ffff8803df9702c0 0000000100000000 0000000000001000
[ 1489.425454]  0000000000000000 ffff8804445d38d8 ffffffffa0e0e878 ffff8804445d3968
[ 1489.433582]  ffffffffa0e0ee3a ffff8803df97b968 ffff8803df9702c0 0000000000000000
[ 1489.441750] Call Trace:
[ 1489.444444]  [<ffffffff812e12b1>] ? __rb_insert_augmented+0xe1/0x1d0
[ 1489.451411]  [<ffffffffa0e0e878>] drm_mm_interval_tree_add_node+0xc8/0xe0 [drm]
[ 1489.459413]  [<ffffffffa0e0ee3a>] drm_mm_insert_node_in_range+0x23a/0x4a0 [drm]
[ 1489.467498]  [<ffffffffa0eecd7f>] i915_gem_gtt_insert+0xaf/0x1b0 [i915]
[ 1489.474785]  [<ffffffffa0f02771>] __i915_vma_do_pin+0x381/0x490 [i915]
[ 1489.482008]  [<ffffffffa0f0a9b2>] logical_render_ring_init+0x2f2/0x3b0 [i915]
[ 1489.489882]  [<ffffffffa0f08e40>] ? gen8_init_rcs_context+0x50/0x50 [i915]
[ 1489.497466]  [<ffffffffa0f04bcc>] intel_engines_init+0x4c/0xc0 [i915]
[ 1489.504581]  [<ffffffffa0ef45b3>] i915_gem_init+0x183/0x520 [i915]
[ 1489.511437]  [<ffffffffa0f71b80>] ? intel_setup_gmbus+0x210/0x290 [i915]
[ 1489.518789]  [<ffffffffa0e0b3ae>] ? drm_irq_install+0xbe/0x140 [drm]
[ 1489.525827]  [<ffffffffa0eaf95d>] i915_driver_load+0xb6d/0x1660 [i915]
[ 1489.533036]  [<ffffffffa0eba5b2>] i915_pci_probe+0x22/0x40 [i915]
[ 1489.539727]  [<ffffffff813207b0>] pci_device_probe+0x90/0x100
[ 1489.546024]  [<ffffffff813b5113>] driver_probe_device+0x1c3/0x280
[ 1489.552702]  [<ffffffff813b5249>] __driver_attach+0x79/0x80
[ 1489.558766]  [<ffffffff813b51d0>] ? driver_probe_device+0x280/0x280
[ 1489.565628]  [<ffffffff813b32e9>] bus_for_each_dev+0x69/0xa0
[ 1489.571830]  [<ffffffff813b4a59>] driver_attach+0x19/0x20
[ 1489.577765]  [<ffffffff813b46ac>] bus_add_driver+0x19c/0x1e0
[ 1489.583940]  [<ffffffffa0fe9000>] ? 0xffffffffa0fe9000
[ 1489.589550]  [<ffffffff813b59eb>] driver_register+0x6b/0xc0
[ 1489.595656]  [<ffffffff8131f251>] __pci_register_driver+0x41/0x50
[ 1489.602388]  [<ffffffffa0fe9029>] i915_init+0x29/0x4a [i915]
[ 1489.608592]  [<ffffffff81000340>] do_one_initcall+0x80/0x130
[ 1489.614766]  [<ffffffff811616e9>] ? __vunmap+0x99/0xf0
[ 1489.620388]  [<ffffffff8116f9cd>] ? kfree+0x13d/0x160
[ 1489.625898]  [<ffffffff810bdb3b>] do_init_module+0x5b/0x1d0
[ 1489.632008]  [<ffffffff810bf914>] load_module+0x1be4/0x2080
[ 1489.638107]  [<ffffffff810bc7c0>] ? __symbol_put+0x40/0x40
[ 1489.644104]  [<ffffffff811899bc>] ? kernel_read+0x3c/0x50
[ 1489.650010]  [<ffffffff810bff6d>] SYSC_finit_module+0x7d/0xa0
[ 1489.656279]  [<ffffffff810bffa9>] SyS_finit_module+0x9/0x10
[ 1489.662371]  [<ffffffff8156c84a>] entry_SYSCALL_64_fastpath+0x1e/0x8e
[ 1489.669405] Code:  Bad RIP value.
[ 1489.673085] RIP  [<          (null)>]           (null)
[ 1489.678742]  RSP <ffff8804445d38a0>
[ 1489.682571] CR2: 0000000000000000
[ 1489.686206] ---[ end trace 1a931c9174ed4834 ]---
[ 1489.898256] ------------[ cut here ]------------
[ 1489.903317] WARNING: CPU: 3 PID: 21816 at kernel/softirq.c:150 __local_bh_enable_ip+0x61/0x90()
[ 1489.912824] Modules linked in: i915(E+) video(E) backlight(E) iosf_mbi(E) drm_kms_helper(E) drm(E) i2c_algo_bit(E) fb(E) nfnetlink xfrm_user xfrm_algo fuse xt_ipvs ip_vs_rr ip_vs xt_mark iptable_mangle br_netfilter bridge stp aufs macvlan veth xt_conntrack xt_addrtype nf_conntrack_ipv6 nf_defrag_ipv6 ip6table_filter ip6_tables ipt_MASQUERADE xt_REDIRECT nf_nat_masquerade_ipv4 xt_nat iptable_nat nf_nat_ipv4 nf_nat_redirect nf_nat xt_recent xt_iprange xt_limit xt_state xt_tcpudp xt_multiport xt_LOG nf_conntrack_ipv4 nf_defrag_ipv4 nf_conntrack iptable_filter ip_tables x_tables 8021q vhost_scsi(O) vhost(O) tcm_loop(O) iscsi_target_mod(O) target_core_user(O) target_core_ep(O) target_core_multi_file(O) target_core_file(O) target_core_iblock(O) target_core_mod(O) syno_extent_pool(PO) rodsp_ep(O) udf isofs
[ 1489.991562]  synoacl_vfs(PO) raid456 async_raid6_recov async_memcpy async_pq async_xor xor async_tx raid6_pq leds_lp3943 aesni_intel glue_helper lrw gf128mul ablk_helper geminilake_synobios(PO) usblp zram syscopyarea sysfillrect sysimgblt fb_sys_fops cfbfillrect cfbcopyarea cfbimgblt drm_panel_orientation_quirks fbdev uhci_hcd r8168(O) sg dm_snapshot dm_bufio crc_itu_t crc_ccitt psnap p8022 llc hfsplus md4 hmac sit tunnel4 ipv6 flashcache_syno(O) flashcache(O) syno_flashcache_control(O) dm_mod arc4 crc32c_intel cryptd ecb aes_x86_64 authenc des_generic ansi_cprng cts md5 cbc cpufreq_powersave cpufreq_performance processor cpufreq_stats ip_tunnel vfat fat loop sha256_generic synorbd(PO) synofsbd(PO) hid_generic usbhid usb_storage hid e1000e(OE) r8125(OE) ixgbe(OE) etxhci_hcd vxlan ip6_udp_tunnel udp_tunnel
[ 1490.069886]  button xhci_pci xhci_hcd ehci_pci ehci_hcd usbcore usb_common [last unloaded: fb]
[ 1490.078093] CPU: 3 PID: 21816 Comm: insmod Tainted: P      D    OE   4.4.180+ #42962
[ 1490.086554] Hardware name: To Be Filled By O.E.M. To Be Filled By O.E.M./Z490M-ITX/ac, BIOS P1.30 06/05/2020
[ 1490.097268]  0000000000000000 ffff8804445d3590 ffffffff812dc11b 0000000000000009
[ 1490.105473]  0000000000000000 ffff8804445d35c8 ffffffff8104fdd2 0000000000000200
[ 1490.113649]  ffff880446278000 0000000000000001 0000000000000000 ffff880457fff868
[ 1490.121819] Call Trace:
[ 1490.124503]  [<ffffffff812dc11b>] dump_stack+0x4d/0x72
[ 1490.130133]  [<ffffffff8104fdd2>] warn_slowpath_common+0x82/0xa0
[ 1490.136707]  [<ffffffff8104fea5>] warn_slowpath_null+0x15/0x20
[ 1490.143080]  [<ffffffff810536f1>] __local_bh_enable_ip+0x61/0x90
[ 1490.149622]  [<ffffffff8156c3d5>] _raw_spin_unlock_bh+0x15/0x20
[ 1490.156095]  [<ffffffff810cbcc0>] cgroup_exit+0x50/0xc0
[ 1490.161821]  [<ffffffff810525a5>] do_exit+0x2a5/0xa10
[ 1490.167342]  [<ffffffff8109833f>] ? kmsg_dump+0x8f/0xb0
[ 1490.173050]  [<ffffffff81007b95>] oops_end+0x85/0xa0
[ 1490.178463]  [<ffffffff8103da5c>] no_context+0x12c/0x1d0
[ 1490.184285]  [<ffffffff8103dc21>] __bad_area_nosemaphore+0x121/0x180
[ 1490.191241]  [<ffffffff8103dc8e>] bad_area_nosemaphore+0xe/0x10
[ 1490.197703]  [<ffffffff8103dedb>] __do_page_fault+0x8b/0x3d0
[ 1490.203888]  [<ffffffff8103e22c>] do_page_fault+0xc/0x10
[ 1490.209678]  [<ffffffff8156e652>] page_fault+0x22/0x30
[ 1490.215320]  [<ffffffffa0e0e470>] ? drm_ht_remove_key+0x70/0x70 [drm]
[ 1490.222370]  [<ffffffff812e12b1>] ? __rb_insert_augmented+0xe1/0x1d0
[ 1490.229337]  [<ffffffffa0e0e878>] drm_mm_interval_tree_add_node+0xc8/0xe0 [drm]
[ 1490.237332]  [<ffffffffa0e0ee3a>] drm_mm_insert_node_in_range+0x23a/0x4a0 [drm]
[ 1490.245403]  [<ffffffffa0eecd7f>] i915_gem_gtt_insert+0xaf/0x1b0 [i915]
[ 1490.252721]  [<ffffffffa0f02771>] __i915_vma_do_pin+0x381/0x490 [i915]
[ 1490.259940]  [<ffffffffa0f0a9b2>] logical_render_ring_init+0x2f2/0x3b0 [i915]
[ 1490.267828]  [<ffffffffa0f08e40>] ? gen8_init_rcs_context+0x50/0x50 [i915]
[ 1490.275461]  [<ffffffffa0f04bcc>] intel_engines_init+0x4c/0xc0 [i915]
[ 1490.282602]  [<ffffffffa0ef45b3>] i915_gem_init+0x183/0x520 [i915]
[ 1490.289436]  [<ffffffffa0f71b80>] ? intel_setup_gmbus+0x210/0x290 [i915]
[ 1490.296776]  [<ffffffffa0e0b3ae>] ? drm_irq_install+0xbe/0x140 [drm]
[ 1490.303794]  [<ffffffffa0eaf95d>] i915_driver_load+0xb6d/0x1660 [i915]
[ 1490.311004]  [<ffffffffa0eba5b2>] i915_pci_probe+0x22/0x40 [i915]
[ 1490.317691]  [<ffffffff813207b0>] pci_device_probe+0x90/0x100
[ 1490.323989]  [<ffffffff813b5113>] driver_probe_device+0x1c3/0x280
[ 1490.330633]  [<ffffffff813b5249>] __driver_attach+0x79/0x80
[ 1490.336732]  [<ffffffff813b51d0>] ? driver_probe_device+0x280/0x280
[ 1490.343582]  [<ffffffff813b32e9>] bus_for_each_dev+0x69/0xa0
[ 1490.349770]  [<ffffffff813b4a59>] driver_attach+0x19/0x20
[ 1490.355642]  [<ffffffff813b46ac>] bus_add_driver+0x19c/0x1e0
[ 1490.361792]  [<ffffffffa0fe9000>] ? 0xffffffffa0fe9000
[ 1490.367407]  [<ffffffff813b59eb>] driver_register+0x6b/0xc0
[ 1490.373489]  [<ffffffff8131f251>] __pci_register_driver+0x41/0x50
[ 1490.380236]  [<ffffffffa0fe9029>] i915_init+0x29/0x4a [i915]
[ 1490.386432]  [<ffffffff81000340>] do_one_initcall+0x80/0x130
[ 1490.392619]  [<ffffffff811616e9>] ? __vunmap+0x99/0xf0
[ 1490.398250]  [<ffffffff8116f9cd>] ? kfree+0x13d/0x160
[ 1490.403778]  [<ffffffff810bdb3b>] do_init_module+0x5b/0x1d0
[ 1490.409868]  [<ffffffff810bf914>] load_module+0x1be4/0x2080
[ 1490.415960]  [<ffffffff810bc7c0>] ? __symbol_put+0x40/0x40
[ 1490.421954]  [<ffffffff811899bc>] ? kernel_read+0x3c/0x50
[ 1490.427837]  [<ffffffff810bff6d>] SYSC_finit_module+0x7d/0xa0
[ 1490.434116]  [<ffffffff810bffa9>] SyS_finit_module+0x9/0x10
[ 1490.440215]  [<ffffffff8156c84a>] entry_SYSCALL_64_fastpath+0x1e/0x8e
[ 1490.447264] ---[ end trace 1a931c9174ed4835 ]---

**Comment by fbelavenuto** [comment] 2023-01-12 20:00
Closing, original problem solved

**Closed by fbelavenuto** 2023-01-12 20:00 UTC
